# Generated by Django 5.2.4 on 2025-07-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseincome',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenseincome',
            name='tax_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=10),
        ),
        migrations.AlterField(
            model_name='expenseincome',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6),
        ),
    ]
